version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=host.docker.internal
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - PORT=${PORT}
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app/server
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:3000