CREATE TABLE diocese_boundaries (
    id SERIAL PRIMARY KEY,
    diocese_name VARCHAR(255) NOT NULL,
    diocese_id VARCHAR(50) NOT NULL,
    boundary_coordinates JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
